sudo: false
addons:
  postgresql: "9.6"
language: python
install: pip install -U pip tox
before_script:
  - psql -c "CREATE ROLE someuser WITH LOGIN PASSWORD 'somepass' CREATEDB;" -U postgres
  - psql -c "CREATE ROLE otheruser WITH LOGIN CREATEDB;" -U postgres
script: tox
matrix:
  allow_failures:
    - env: TOXENV=py35-djmaster
    - env: TOXENV=py36-djmaster
    - env: TOXENV=py37-djmaster
  include:
    - python: 3.5
      env: TOXENV=py35-dj111
    - python: 3.5
      env: TOXENV=py35-dj20
    - python: 3.5
      env: TOXENV=py35-djmaster
    - python: 3.6
      env: TOXENV=py36-dj20
    - python: 3.6
      env: TOXENV=py36-djmaster
    - python: 3.7-dev
      env: TOXENV=py37-dj20
    - python: 3.7-dev
      env: TOXENV=py37-djmaster
    - python: 3.5
      env: TOXENV=flake8
    - python: 3.5
      env: TOXENV=isort
notifications:
  email: false
